### ISSUE TITLE
Restrictive upper version bounds

### ISSUE THREAD

**Issue by expipiplus1** [roelvandijk/numerals#15]
These stop numerals from being built with stack, or as part of a package with more recent dependencies, or with the latest ghc.

I've got a fork where these are raised enough to get numerals compiling with stack, however 258 test cases are failing. I'm unable to build numerals without my change so I'm not sure if this is "expected". There are also a bunch of "redundant import" warnings from Prelude too.

My fork is here: https://github.com/expipiplus1/numerals/tree/dep-versions

I didn't want to submit a PR with tests failing though.

**Comment by roelvandijk** [comment]
Thanks for the warning. I'm working towards a new (0.5) release. I already made some large changes, such as moving away from finally-tagless style types to straight data types and dropping the unicode stuff.

The failing test cases are acceptable for the moment.

**Comment by roelvandijk** [comment]
I removed all upper bounds in f7ebf5f905f4a14ed65264fdfaea9fb2f632e5c6. That should make maintenance easier.
